### PR TITLE
Fortune Compat Config

### PR DESCRIPTION
**Pull request by SisterJacq**
That Config I told you I would make :V

### CODE REVIEW

**Comment by SisterJacq** [comment]
ZEROKYUUNI, STAHP BEING A LAZY HELLFEESH!!!!

**Comment by Parker8283** [comment]
(removed for misunderstanding)

**Comment by SisterJacq** [comment]
I troll Zero like this on the #TinkersConstruct IRC all the time, I am not being an ass, you are simply misunderstanding the whole situation, also, is a SINGLE comment enough to calls someone an ass? I know he is busy fixing the Metallurgy compat and adding more sieving things, mostly because I spend time on IRC with him.

**Comment by Parker8283** [comment]
It is my mistake, as more often than not, I see people do this and actually mean it, and not in a joking kind of way. My apologies.

**Comment by SisterJacq** [comment]
Oh, no big deal.

**Pull request merged**
